#
#  _           _    Makefile for jimp API 
#   | . |   | |_|   * 24/01/2002
#  \  | | | | |   
#
all:
	make -C lang
	make -C io
	make -C util

clean:
	make clean -C lang
	make clean -C io
	make clean -C util
